### ISSUE TITLE
Media image bug

### ISSUE THREAD

**Issue by jamyouss** [Synapse-Cmf/synapse-cmf#20]
There is a bug when an image has the same name.
For example if i upload an image named `tmp1.jpeg` twice, i have two entries in the table `synapse_image` but they are linked to the same file in the table `synapse_file`. The first image is overwrited in assets directory.

Use case: Upload the first time on image `tmp1.jpeg` and then another image named also `tmp1.jpeg`.

**Comment by Nyxis** [comment]
Du coup, calculer un sha1 unique (+ microtime) pour renommer le fichier upload.
