### ISSUE TITLE
Problem issue when change template name

### ISSUE THREAD

**Issue by baiiko** [Synapse-Cmf/synapse-cmf#22]
If we change a template name, who has been saved, in yaml file, we catch an error on the panel.

The name is not recogonize from the list.

![capture d ecran de 2016-11-24 15 22 36](https://cloud.githubusercontent.com/assets/3129221/20601634/e130ad56-b259-11e6-9271-6e88fc6915f4.png)

**Comment by Nyxis** [comment]
C'est un comportement attendu : le nom du type de template est sauvegardé avec l'instance en template en base.
Il faut ajouter un message d'erreur si un template en base a un type qui n'existe plus, ou alors implémenter un système d'alias pour les types de template, histoire d'assurer une rétrocompatibilité.

**Comment by Nyxis** [comment]
Corrigé, à partir de maintenant, si un template est chargé mais ne correspond à aucun type de template, une exception est levée, invitant à vérifier les configurations.
