### ISSUE TITLE
Javascript error make submit form impossible

### ISSUE THREAD

**Issue by jamyouss** [Synapse-Cmf/synapse-cmf#23]
I have a javascript error after created a page and add some content.

```
An invalid form control with name='page[synapse][templates][page][zones][content][components][5][data][title]' is not focusable.
An invalid form control with name='page[synapse][templates][page][zones][content][components][7][data][html]' is not focusable.
```

**Comment by Nyxis** [comment]
Il faut intégrer des messages d'erreur lors du submit de champs invalides et invisibles (système de collapse dans le form d'admin).
Ce sera fait avec l'implémentation du futur thème Synapse.
