### ISSUE TITLE
Route déjà utilisé

### ISSUE THREAD

**Issue by baiiko** [Synapse-Cmf/synapse-cmf#24]
Lorsque une route est déjà utilisé nous avons une erreur si nous proposons une nouvelle page avec la même url nous avons une jolie erreur SQL

![capture d ecran de 2016-11-24 15 39 46](https://cloud.githubusercontent.com/assets/3129221/20602280/ddd0727e-b25c-11e6-87d0-fb516a91ab07.png)

**Comment by Nyxis** [comment]
Il faut implémenter un check, et un validateur d'unicité.

**Comment by GuigZ-** [comment]
https://github.com/Synapse-Cmf/synapse-cmf/pull/42
