### ISSUE TITLE
update monolog 2.8 -> 3.0

### ISSUE THREAD

**Issue by holoflins** [Synapse-Cmf/synapse-cmf#34]
Sur le projet PssGen, qui utilise synapse, j'ai besoin de mettre a jour monolog en version 3 suite a des erreurs de deprecated. 

Actuellement synapse me bloque car il necessite la version 2.8 de monolog-bundle

**Comment by Nyxis** [comment]
C'est corrigé, Synapse autorise maintenant monolog dans toute version supérieure à 2.8.
